window.COLORS = [
    {"name": "aqua", "category": "teal"},
    {"name": "aquamarine", "category": "teal"},
    {"name": "azure", "category": "light blue"},
    {"name": "beige", "category": "light orange"},
    {"name": "bisque", "category": "light orange"},
    {"name": "black", "category": "dark green"},
    {"name": "almond", "category": "light orange"},
    {"name": "blue", "category": "blue"},
    {"name": "brown", "category": "dark orange"},
    {"name": "bronze", "category": "dark orange"},
    {"name": "wood", "category": "dark orange"},
    {"name": "chartreuse", "category": "green"},
    {"name": "chocolate", "category": "dark orange"},
    {"name": "coral", "category": "light orange"},
    {"name": "silk", "category": "light orange"},
    {"name": "crimson", "category": "red"},
    {"name": "cyan", "category": "teal"},
    {"name": "brick", "category": "red"},
    {"name": "floral", "category": "violet"},
    {"name": "forest", "category": "green"},
    {"name": "fuchsia", "category": "violet"},
    {"name": "gainsboro", "category": "light blue"},
    {"name": "ghost", "category": "light blue"},
    {"name": "gold", "category": "yellow"},
    {"name": "goldenrod", "category": "yellow"},
    {"name": "gray", "category": "light blue"},
    {"name": "green", "category": "green"},
    {"name": "honeydew", "category": "light blue"},
    {"name": "indigo", "category": "purple"},
    {"name": "ivory", "category": "light blue"},
    {"name": "khaki", "category": "yellow"},
    {"name": "lavender", "category": "purple"},
    {"name": "lawn", "category": "green"},
    {"name": "lemon", "category": "yellow"},
    {"name": "lime", "category": "green"},
    {"name": "linen", "category": "yellow"},
    {"name": "magenta", "category": "violet"},
    {"name": "maroon", "category": "red"},
    {"name": "midnight", "category": "dark green"},
    {"name": "mint", "category": "green"},
    {"name": "misty", "category": "light blue"},
    {"name": "moccasin", "category": "light orange"},
    {"name": "navy", "category": "blue"},
    {"name": "oldlace", "category": "light blue"},
    {"name": "olive", "category": "green"},
    {"name": "orange", "category": "dark orange"},
    {"name": "orchid", "category": "purple"},
    {"name": "papaya", "category": "orange"},
    {"name": "peach", "category": "light orange"},
    {"name": "peru", "category": "dark orange"},
    {"name": "pink", "category": "purple"},
    {"name": "plum", "category": "purple"},
    {"name": "purple", "category": "purple"},
    {"name": "red", "category": "red"},
    {"name": "rose", "category": "violet"},
    {"name": "rosy", "category": "violet"},
    {"name": "royal", "category": "blue"},
    {"name": "saddle", "category": "dark orange"},
    {"name": "salmon", "category": "light orange"},
    {"name": "sandy", "category": "light orange"},
    {"name": "sea", "category": "blue"},
    {"name": "seashell", "category": "yellow"},
    {"name": "sienna", "category": "dark orange"},
    {"name": "silver", "category": "light blue"},
    {"name": "sky", "category": "light blue"},
    {"name": "slate", "category": "light blue"},
    {"name": "snow", "category": "light blue"},
    {"name": "spring", "category": "green"},
    {"name": "steel", "category": "light blue"},
    {"name": "tan", "category": "light orange"},
    {"name": "teal", "category": "teal"},
    {"name": "thistle", "category": "violet"},
    {"name": "tomato", "category": "red"},
    {"name": "turquoise", "category": "teal"},
    {"name": "violet", "category": "violet"},
    {"name": "wheat", "category": "light orange"},
    {"name": "white", "category": "light blue"},
    {"name": "smoke", "category": "light blue"},
    {"name": "yellow", "category": "yellow"}
  ];